### ISSUE TITLE
Tag navigation

### ISSUE THREAD

**Issue by flachware** [tropy/tropy.org#4]
@inukshuk, I followed this documentation for the tag navigation implementation:

https://www.ghostforbeginners.com/how-to-add-a-tag-menu-to-your-blog/

It still lacks an active state. The `{{navigation}}` helper for static pages provides a `current` boolean, but I haven’t found something similar for tags.

Could you please have a look at this matter?

**Comment by inukshuk** [comment]
Closing, because we're using the navigation module instead.
